# Test configuration with different values
simulation:
  max_scenarios: 1
  pool_seed: 1113
  run_seed: 1719
  num_agents: 3

agent_pool:
  size_multiplier: 10
  min_size: 100
  balance_range:
    min: 100
    max: 500

traits:
  mutation_rounds: 20
  proposal_word_range:
    min: 30
    max: 60

consensus:
  assignment_award: 100
  max_feedback_per_agent: 3
  feedback_stake: 10
  proposal_self_stake: 50
  revision_cycles:
    min: 1
    max: 1
  stake_phase_ticks:
    min: 10
    max: 10
  # Phase timeout configurations
  propose_phase_ticks: 5
  feedback_phase_ticks: 4
  revise_phase_ticks: 4
  finalize_phase_ticks: 2
  conviction_params:
    MaxMultiplier: 2.0
    TargetFraction: 0.98

llm:
  issue: true
  proposal: true
  feedback: true
  revise: true
  model : "phi3"
  context_window: 9999

# Debug settings
debug:
  enabled: true
  output_dir: "debug"
  save_context: true

issue:
  problem_statement: "Custom test problem statement."
  background: "Custom test background."
  metadata:
    created_by: "test_runner"
    created_at: "2025-01-01"
