# Test configuration with different values
simulation:
  max_scenarios: 5
  pool_seed: 9999
  run_seed: 8888
  num_agents: 8

agent_pool:
  size_multiplier: 5
  min_size: 50
  balance_range:
    min: 100
    max: 500

traits:
  mutation_rounds: 15
  proposal_word_range:
    min: 30
    max: 60

consensus:
  assignment_award: 200
  max_feedback_per_agent: 5
  feedback_stake: 10
  proposal_self_stake: 75
  revision_cycles:
    min: 2
    max: 4
  staking_rounds:
    min: 5
    max: 8
  conviction_params:
    MaxMultiplier: 1.5
    TargetFraction: 0.95

issue:
  problem_statement: "Custom test problem statement."
  background: "Custom test background."
  metadata:
    created_by: "test_runner"
    created_at: "2025-01-01"